name: 24/7 Faucet Claimer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # يشغل كل 6 ساعات

jobs:
  run-faucet:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # 5 ساعات و50 دقيقة
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run Faucet Claimer
      env:
        FAUCET_EMAIL: ${{ Aliiikrdforbus@gmail.com }}
        FAUCET_PASSWORD: ${{ Zxcvv121221122&& }}
      run: python faucet_claimer.py
