name: Faucet Claimer No Proxy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # كل 6 ساعات

jobs:
  claim:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # 5 ساعات و50 دقيقة

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run Faucet Claimer
      env:
        FAUCET_ACCOUNTS: ${{ secrets.FAUCET_ACCOUNTS }}
      run: python faucet_claimer.py
